name: Sync Upstream to Downstream

env:
  GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
  UPSTREAM_REPO: "j-hc/revanced-magisk-module"
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "main"
  FETCH_ARGS: "--all"
  MERGE_ARGS: "--no-ff"
  PUSH_ARGS: "--force"
  SPAWN_LOGS: "true"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Sync Upstream Action
      uses: ./  
      with:
        upstream_repo: ${{ env.UPSTREAM_REPO }}
        upstream_branch: ${{ env.UPSTREAM_BRANCH }}
        downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
        github_token: ${{ env.GITHUB_TOKEN }}
        fetch_args: ${{ env.FETCH_ARGS }}
        merge_args: ${{ env.MERGE_ARGS }}
        push_args: ${{ env.PUSH_ARGS }}
        spawn_logs: ${{ env.SPAWN_LOGS }}
